### ISSUE TITLE
Compression of something larger than ZLIB_COMPLETE_CHUNK

### ISSUE THREAD

**Issue by DeLadoss** [rudi-cilibrasi/zlibcomplete#1]
Hello,

I tried to compress something larger than ZLIB_COMPLETE_CHUNK and I have a problem.

```
int main(int argc, char **argv)
{
    std::ifstream t("file");
    std::string str;

    t.seekg(0, std::ios::end);
    str.reserve(t.tellg());
    t.seekg(0, std::ios::beg);

    str.assign((std::istreambuf_iterator<char>(t)),
                    std::istreambuf_iterator<char>());

    GZipCompressor compressor(9, auto_flush);
    string output = compressor.compress(str);
    output  += compressor.finish();

    GZipDecompressor decompressor;
    string output2 = decompressor.decompress(output);

    cout << output2;

    return 0;
}
```

After my decompression, the beginning (16384, ZLIB_COMPLETE_CHUNK) is ok but then, I have the beginning of the file again.
The problem is with the compression.

**Comment by DeLadoss** [comment]
In zlibtop.cpp:

line 39:
`memcpy(in_, input.data(), howManyWanted);`

should be replaced by:
`memcpy(in_, input.data()+i, howManyWanted);`

**Comment by DeLadoss** [comment]
it also needs the same correction for the decompression

**Comment by rudi-cilibrasi** [comment]
Thanks, DeLadoss!  I have incorporated your bugfix into the 1.0.3 release and also improved the flush logic accordingly to improve compression ratio.  I appreciate your great bug report!
