### ISSUE TITLE
Bug ZLibBaseCompressor::baseFinish

### ISSUE THREAD

**Issue by DeLadoss** [rudi-cilibrasi/zlibcomplete#3]
Hi,

There is no check on the value of strm_.avail_out in this function. This means it can happen (and it has for me) you don't get the full encoded string after calling the baseFinish function (in reality after calling the finish() function).

Thus, this part of the baseFinish function:

```
      strm_.avail_out = ZLIB_COMPLETE_CHUNK;
      strm_.next_out = (Bytef *) out_;
      retval = deflate(&strm_, Z_FINISH);
      if (retval == Z_STREAM_ERROR) {
          throw std::bad_alloc();
      }
      have = ZLIB_COMPLETE_CHUNK - strm_.avail_out;
      result += std::string(out_, have);
```

should be replaced by:

```
  do {
      strm_.avail_out = ZLIB_COMPLETE_CHUNK;
      strm_.next_out = (Bytef *) out_;
      retval = deflate(&strm_, Z_FINISH);
      if (retval == Z_STREAM_ERROR) {
          throw std::bad_alloc();
      }
      have = ZLIB_COMPLETE_CHUNK - strm_.avail_out;
      result += std::string(out_, have);
  } while(strm_.avail_out == 0);
```

**Comment by rudi-cilibrasi** [comment]
Thank you again for your great work!  I have fixed it according to your bug report in v1.0.4.  There is also a new download link with the automake package in addition to the regular github type releases.
