### ISSUE TITLE
Data is copied/allocated unnecessarily, due to std::string API

### ISSUE THREAD

**Issue by snej** [rudi-cilibrasi/zlibcomplete#7]
Using std::string as the data format in the API means unavoidable memory copying and allocation in most cases. If the caller's data is in any other form, it has to construct a new std::string object to pass it to zlibcomplete, which involves allocating a new copy of the data on the heap. Similarly, zlibcomplete returns std::strings which means the result data always ends up allocated on the heap and has to be copied elsewhere by the caller.

In most situations this overhead won't be noticeable. But compression/decompression can become a CPU bottleneck in some areas, and in that case it's important to cut out any unnecessary memory allocation or copying.

I suggest having the core implementation use direct pointers to the data, and then implementing the existing string-based API as a simple wrapper around that. Then clients can choose performance or convenience.

**Comment by rudi-cilibrasi** [comment]
I agree with this analysis.  I think the only thing slowing down a great solution is that it may be a fair amount of work.  In other words, there is already a very hard to use raw pointer library which is the old zlib. It is pretty hard to use but supports the high efficiency use-case you mention.  This zlibcomplete is indeed a wrapper around it that sacrifices efficiency (primarily through std::string as you correctly point out) for convenience so is an instance of the "Facade" design pattern.  It seems you are suggesting another library that may fit sort of inbetween these two.  What form do you think it should take?  A separate github repo that is a C-language wrapper for zlib? Or a C++ version that uses raw pointers but makes it easier to use somehow?  That is something I could believe in once I see it however working out the specific interface .h file is slightly daunting to me.  If you have an idea of the kind of interface you would like to see based on what you need in your application or maybe what you have already imagined / designed / prototypes I would love to see it or maybe work with you in more detail on it through PR's together etc.

**Comment by snej** [comment]
Well, in my code I use a type I created called `slice` which is just a pointer/size pair. You can see it [here](https://github.com/couchbaselabs/fleece/blob/master/Fleece/slice.hh#L52-L54). It points to a range of memory, with no ownership implied. Very useful.

I'm not expecting you to adopt the full slice API, but it would be easy to just add the basic struct declaration, plus a constructor that takes a string parameter. Then the _input_ side would be easy: the input parameters are slices, but the client can pass std::strings if they want just like today.

The output side is harder. You need some kind of growable buffer, but there are so many different kinds. It might work best to provide a template so the client can parameterize it with their favorite output format, defaulting to `string`.

**Comment by rudi-cilibrasi** [comment]
I have absolutely used such a struct myself (void/char *buf, int len)  in the past indeed in my "libcomplearn" software so I totally agree with the desire. I wonder if you would be able to supply a PR to get the ball rolling?

**Comment by rudi-cilibrasi** [comment]
one other possibility is that we just improve the current std::string api to use the new rvalue references / move semantics in c++ 2011 and later.  then the extra allocation can be avoided i believe isn't that correct? maybe a simpler way to achieve the same performance boost.

**Comment by rudi-cilibrasi** [comment]
closed due to insufficient interest. happy to reopen if/when somebody wants to work with me on this more challenging enhancement which may or may not be easy enough to be in the scope of this library
